#!/bin/bash
##########NOTES for NAGIOS WEB GUI SERVICES THAT ARE NOT GREEN##########

##########TROUBLESHOOTING SERVER##########
###CONFIRM NAGIOS CONFIG on SERVER###
/usr/sbin/nagios -v /etc/nagios/nagios.cfg

##########TROUBLESHOOTING CLIENT##########
###SERVER CHECKS to be done on NAGIOS SERVER#####
##WANT OKS AS RESPONSE FROM FOLLOWING##
/usr/lib64/nagios/plugins/check_nrpe -H <client internal ip address> -c check_load
/usr/lib64/nagios/plugins/check_nrpe -H <client internal ip address> -c check_mem
##IF ANYTHING BUT OKS, NEED TO UPDATE COMMANDS IN NRPE.CFG FILE ON CLIENT##
##STARTING AT LINE 319, UNCOMMENTS AND MAKE CHANGES AS LISTED BELOW IN SED STATEMENTS
vim /etc/nagios/nrpe.cfg
##TO AUTOMATE##
sed -i 's|#command[check_mem]=/usr/lib64/nagios/plugins/custom_check_mem -n $ARG1$|command[check_mem]=/usr/lib64/nagios/plugins/check_mem.sh -w 80 -c 90|g' /etc/nagios/nrpe.cfg
sed -i 's|#command[check_users]=/usr/lib64/nagios/plugins/check_users $ARG1$|command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10|g' /etc/nagios/nrpe.cfg
sed -i 's|#command[check_load]=/usr/lib64/nagios/plugins/check_load $ARG1$|command[check_load]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20|g' /etc/nagios/nrpe.cfg
sed -i 's|#command[check_disk]=/usr/lib64/nagios/plugins/check_disk $ARG1$|command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10%|g' /etc/nagios/nrpe.cfg
sed -i 's|#command[check_swap]=/usr/lib64/nagios/plugins/check_swap $ARG1$|command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%|g' /etc/nagios/nrpe.cfg
sed -i 's|#command[check_cpu_stats]=/usr/lib64/nagios/plugins/check_cpu_stats.sh $ARG1$|command[check_cpu_stats]=/usr/lib64/nagios/plugins/check_cpu_stats.sh -w 70,40,30 -c 90,50,40|g' /etc/nagios.nrpe.cfg

##https://rafishaikblog.wordpress.com/2017/08/14/nagios-plugins-functionality/

##########SED STATEMENT CHEATSHEET##########
:  # label
=  # line_number
a  # append_text_to_stdout_after_flush
b  # branch_unconditional             
c  # range_change                     
d  # pattern_delete_top/cycle          
D  # pattern_ltrunc(line+nl)_top/cycle 
g  # pattern=hold                      
G  # pattern+=nl+hold                  
h  # hold=pattern                      
H  # hold+=nl+pattern                  
i  # insert_text_to_stdout_now         
l  # pattern_list                       
n  # pattern_flush=nextline_continue   
N  # pattern+=nl+nextline              
p  # pattern_print                     
P  # pattern_first_line_print          
q  # flush_quit                        
r  # append_file_to_stdout_after_flush 
s  # substitute                                          
t  # branch_on_substitute              
w  # append_pattern_to_file_now         
x  # swap_pattern_and_hold             
y  # transform_chars  
,  # seperator
|  # seperator
/  # seperator
:  # seperator
\  # escape symbol when / is also part of line--goes before: sed -i 's/some text path\/with a sub text path/new text to be replaced\/with new sub text/g' /file/path
